import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class LoginFrame extends javax.swing.JFrame {

    private static final Logger logger = Logger.getLogger(LoginFrame.class.getName());

    public LoginFrame() {
        initComponents();
        setLocationRelativeTo(null);
    }

    private void checkLogin() {
        try {
            String sql = "SELECT * FROM login WHERE uname=? AND pwd=?";
            Connection con = DBUtility.getConnection();
            PreparedStatement ps = con.prepareStatement(sql);
            ps.setString(1, jTextField1.getText());
            ps.setString(2, new String(jPasswordField1.getPassword()));
            ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                new DashboardFrame();
                dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Invalid Username or Password");
            }
        } catch (SQLException ex) {
            logger.log(Level.SEVERE, null, ex);
        }
    }
    // ... (initComponents, main method, and variables declaration - generated by NetBeans)
}